# Databricks notebook source
# MAGIC %md
# MAGIC #Magnitude Analysis
# MAGIC #####Purpose:
# MAGIC - To quantify data and group results by specific dimensions.
# MAGIC - For understanding data distribution across categories.
# MAGIC 	
# MAGIC #####SQL Functions Used:
# MAGIC - Aggregate Functions: SUM(), COUNT(), AVG()
# MAGIC - GROUP BY, ORDER BY
# MAGIC ##### Dividing Aggregated [Measure] By [Dimension]
# MAGIC - Total Sales By Country
# MAGIC - Total Quantity By Category
# MAGIC - Average Price By Product
# MAGIC - Total Orders By Customer

# COMMAND ----------

# MAGIC %md
# MAGIC ####Find total customers by countries

# COMMAND ----------

query = """
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
"""
df = spark.sql(query)

df.display()

# COMMAND ----------

# MAGIC %md
# MAGIC ####Find total customers by gender

# COMMAND ----------

query = """
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC
"""
df = spark.sql(query)

df.display()

# COMMAND ----------

# MAGIC %md
# MAGIC ####Find total products by category

# COMMAND ----------

query = """
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC
"""
df = spark.sql(query)

df.display()

# COMMAND ----------

# MAGIC %md
# MAGIC ####What is the average costs in each category?

# COMMAND ----------

query = """
SELECT
    category,
    ROUND(AVG(product_cost), 0) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC
"""
df = spark.sql(query)

df.display()

# COMMAND ----------

# MAGIC %md
# MAGIC ####What is the total revenue generated for each category?

# COMMAND ----------

query = """
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM .gold.fact_sales AS f
LEFT JOIN .gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC
"""
df = spark.sql(query)

df.display()

# COMMAND ----------

# MAGIC %md
# MAGIC ####What is the total revenue generated by each customer?

# COMMAND ----------

query = """
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC
"""
df = spark.sql(query)

df.limit(10).display()

# COMMAND ----------

# MAGIC %md
# MAGIC ####What is the distribution of sold items across countries?

# COMMAND ----------

query = """
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY
    c.country
ORDER BY total_sold_items DESC
"""
df = spark.sql(query)

df.display()